module.exports.eventsNames = [
    "Reunión de Planificación Semanal",
"Revisión de Documentación Técnica",
"Entrevista con el Cliente",
"Evaluación de Riesgos",
"Capacitación del Equipo",
"Presentación del Anteproyecto",
"Pruebas de Validación",
"Revisión de Presupuesto",
"Actualización del Cronograma",
"Sesión de Brainstorming",
"Reunión de Retroalimentación",
"Sesión de Priorización",
"Revisión de Requisitos",
"Sesión de Diseño Conceptual",
"Preparación de Informes de Progreso",
"Sesión de Pruebas de Concepto",
"Reunión de Evaluación de Recursos",
"Planificación de Comunicaciones",
"Revisión de Hitos",
"Sesión de Resolución de Problemas"
]
module.exports.eventsDescriptions = [
    
"Simula una reunión donde se planifican las tareas de la semana, como la asignación de recursos y la actualización de la base de datos de proyectos",
"Representa la revisión de documentación técnica relacionada con un proyecto y la actualización de registros en la base de datos con la información revisada",
"Este evento refleja una interacción con el cliente para recopilar información actualizada o nuevos requisitos que se deben registrar en la base de datos",
"Simula la identificación y evaluación de riesgos en un proyecto, con la posterior documentación de estos riesgos en la base de datos",
"Indica una sesión de capacitación para el equipo de proyecto, donde se pueden registrar los participantes y los detalles relacionados en la base de datos de capacitación",
"Representa la presentación de un anteproyecto a partes interesadas, y se puede utilizar para registrar comentarios y decisiones en la base de datos",
"Indica la fase de pruebas de validación de un proyecto, donde se registran los resultados de las pruebas en la base de datos",
"Simula la revisión y actualización del presupuesto de un proyecto, con el registro de cambios en la base de datos financiera",
"Este evento refleja la actualización del cronograma del proyecto y la modificación correspondiente de las fechas en la base de datos",
"Indica una sesión creativa de lluvia de ideas, donde se pueden registrar ideas y conceptos relevantes en la base de datos"
]
module.exports.getRandomDate = () =>{
    const year = 2023;
    const month = Math.floor(Math.random() * 12) + 1;
    const day = Math.floor(Math.random() * 31) + 1;
    const hour = Math.floor(Math.random() * 24); // Ajustado para 0-23
    const minute = Math.floor(Math.random() * 60); // Ajustado para 0-59
    const date = new Date(year, month - 1, day, hour, minute);
    return date; 
    
}
module.exports.studentNames = [
    "Juan",
    "Pedro",
    "Luis",
    "Carlos",
    "Jorge",
    "Andres",
    "Jose",
    "Maria",
    "Fernanda",
    "Sofia",
    "Camila",
    "Laura",
    "Valentina",
    "Sara",
    "Paula",
    "Juliana",
    "Daniela",
    "Ana",
    "Mariana",
    "Alejandra",
    "Catalina",
    "Isabella",
    "Antonia",
    "Valeria",
    "Luciana",
    "Gabriela",
]
module.exports.carnets = [
    2020123456,
    2020121226,
    2020123457,
    2020123458,
    2020123459,
    2020123460,
    2020123461,
    2020123462,
    2020123463,
    2020123464,
    2020123465,
    2020123466,
    2020123467,
    2020123468,
    2020123469,
    2020123470,
    2020123471,
    2020123472,
    2020123473,
    2020123474,
    2020123475,
    2020123476,
    2020123477,
    2020123478,
    2020123479,
    2020123480,
    2020123481,
    2020123482,
    2020123483,
    2020123484,
    2020123485,
    2020123486,
    2020123487,
    2020123488,
    2020123489,
    2020123490,
    2020123491,
    2020123492,
    2020123493,
    2020123494,
    2020123495,
    2020123496,
]
module.exports.direccion = [
    "San Salvador",
    "San Miguel",
    "Santa Ana",
    "Ahuachapán",
    "Sonsonate",
    "La Unión",
    "La Libertad",
    "Chalatenango",
    "Cuscatlán",
    "La Paz",
    "Cabañas",
    "Usulután",
    "Morazán",
]
module.exports.nombreProyecto = [
    "Sistema de Gestión de Proyectos",
    "Sistema de Gestión de Recursos Humanos",
    "Sistema de Gestión de Recursos Financieros",
    "Sistema de Gestión de Recursos Materiales",
    "Sistema de Gestión de Recursos Tecnológicos",
    "Sistema de Gestión de Recursos Técnicos",
    "Sistema de Gestión de Recursos Físicos",
    "Sistema de Gestión de Recursos Naturales",
    "Sistema de Gestión de Recursos Energéticos",
    "Sistema de Gestión de Recursos Ambientales",
    "Sistema de Gestión de Recursos de Información",
    "Sistema de Gestión de Recursos de Conocimiento",
    "Sistema de Gestión de Recursos de Capital",
    "Sistema de Gestión de Recursos de Capital Humano",
    "Sistema de Gestión de Recursos de Capital Social",
    "Sistema de Gestión de Recursos de Capital Natural",
]
module.exports.nombreEmpresa = [
    "Microsoft",
    "Google",
    "Apple",
    "Amazon",
    "Facebook",
    "Alphabet",
    "Alibaba",
    "Tencent",
    "Tesla",
    "Netflix",
    "Adobe",
    "Oracle",
    "IBM",
    "Intel",
    "Cisco",
    "Salesforce",
    "SAP",
    "Nvidia",
    "PayPal",
    "Qualcomm",
    "Sony",
    "Nintendo",
    "Spotify",
    "Uber",
    "Airbnb"


]